# Generated by Django 5.2.1 on 2025-06-04 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('death_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('Parent', 'Родитель'), ('Child', 'Ребенок'), ('Sibling', 'Брат/Сестра'), ('Spouse', 'Супруг/Супруга'), ('Grandparent', 'Дедушка/Бабушка'), ('Grandchild', 'Внук/Внучка'), ('Cousin', 'Двоюродный брат/сестра'), ('Uncle_Aunt', 'Дядя/Тётя'), ('Nephew_Niece', 'Племянник/Племянница'), ('In_Law', 'Свойственник (Свёкор, Тесть, и т.д.)'), ('Godparent', 'Крёстный родитель'), ('Godchild', 'Крестник'), ('Matchmaker', 'Сват/Сваха'), ('Friend', 'Друг'), ('Acquaintance', 'Знакомый'), ('Other', 'Другое')], max_length=20, verbose_name='Тип родства')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='genealogy.person', verbose_name='От кого')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='genealogy.person', verbose_name='К кому')),
            ],
        ),
    ]
